services:
  uba_leitor:
    build: .
    container_name: uba_leitor
    ports:
      - "2000:8080"

    environment:
      - DB_HOST=example.com
      - DB_PORT=1000
      - DB_DATABASE=db_name
      - DB_USER=db_user
      - DB_PASSWORD=db_password

    restart: always